DROP TABLE IF EXISTS FX_from_USD;
DROP TABLE IF EXISTS FX_to_USD;

CREATE TABLE IF NOT EXISTS FX_from_USD(
    `date`  DATE NOT NULL PRIMARY KEY,
    EUR DOUBLE,
    JPY DOUBLE,
    BGN DOUBLE,
    CZK DOUBLE,
    DKK DOUBLE,
    GBP DOUBLE,
    HUF DOUBLE,
    PLN DOUBLE,
    RON DOUBLE,
    SEK DOUBLE,
    CHF DOUBLE,
    ISK DOUBLE,
    NOK DOUBLE,
    HRK DOUBLE,  
    RUB DOUBLE,  
    TRL DOUBLE,  
    TRY DOUBLE,
    AUD DOUBLE,
    DRL DOUBLE,
    CAD DOUBLE,
    CNY DOUBLE,
    HKD DOUBLE,
    IDR DOUBLE,
    ILS DOUBLE,
    INR DOUBLE,
    KRW DOUBLE,
    MXN DOUBLE,
    MYR DOUBLE,
    NZD DOUBLE,
    PHP DOUBLE,
    SGD DOUBLE,
    THB DOUBLE,
    ZAR DOUBLE
);

CREATE TABLE IF NOT EXISTS FX_to_USD(
    `date`  DATE NOT NULL PRIMARY KEY,
    EUR DOUBLE,
    JPY DOUBLE,
    BGN DOUBLE,
    CZK DOUBLE,
    DKK DOUBLE,
    GBP DOUBLE,
    HUF DOUBLE,
    PLN DOUBLE,
    RON DOUBLE,
    SEK DOUBLE,
    CHF DOUBLE,
    ISK DOUBLE,
    NOK DOUBLE,
    HRK DOUBLE,  
    RUB DOUBLE,  
    TRL DOUBLE,  
    TRY DOUBLE,
    AUD DOUBLE,
    DRL DOUBLE,
    CAD DOUBLE,
    CNY DOUBLE,
    HKD DOUBLE,
    IDR DOUBLE,
    ILS DOUBLE,
    INR DOUBLE,
    KRW DOUBLE,
    MXN DOUBLE,
    MYR DOUBLE,
    NZD DOUBLE,
    PHP DOUBLE,
    SGD DOUBLE,
    THB DOUBLE,
    ZAR DOUBLE
);

LOAD DATA LOCAL INFILE 'C:/Users/expos/Desktop/FX_from_USD.csv'
INTO TABLE FX_from_USD
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY " "
LINES TERMINATED BY '\n'
IGNORE 2 LINES;

LOAD DATA LOCAL INFILE 'C:/Users/expos/Desktop/FX_to_USD.csv'
INTO TABLE FX_to_USD
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY " "
LINES TERMINATED BY '\n'
IGNORE 2 LINES;
